theme: jekyll-theme-modernist
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: "EC M202A Final Project"
description: "Course project website for EC M202A / CS M213A"
# For user pages, url should be "https://username.github.io" and baseurl: ""
# For project pages hosted at "https://username.github.io/repo-name", set url
# to "https://username.github.io" and baseurl to "/repo-name" so absolute_url works.
url: "https://skyguy126.github.io"
baseurl: "/traffic_inference"

markdown: GFM

# Necessary for GitHub Pages
plugins: []
