theme: jekyll-theme-modernist
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: "EC M202A Project â€“ Project Title"
description: "Course project website for EC M202A / CS M213A"
# For user pages, url should be "https://username.github.io" and baseurl: ""
# For project pages, url: "https://username.github.io" and baseurl: "/repo-name"
url: "https://skyguy126.github.io/"        # replace UCLA-ECEM202A with your github id
baseurl: "/ECM202A_2025Fall_Project_6"    # replace ecem202a_project with your project name, e.g., "/ECEM202A_2025Fall_Project_1"

markdown: kramdown
kramdown:
  input: GFM

# Necessary for GitHub Pages
plugins: []